version: "3"

volumes:
  target-files:
  results-files:

services:
  katana:
    build:
      context: .
      dockerfile: docker\Dockerfile
    volumes:
      - ./examples:/examples
      - target-files:/data/targets
      - results-files:/data/results
